\set ON_ERROR_STOP off

\echo
\echo 'CREATE TABLE IF NOT EXISTS available_tool ('
\echo '    tool_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,'
\echo '    tool_type TEXT NOT NULL,'
\echo '    available INTEGER DEFAULT 5 NOT NULL,'
\echo '    CHECK(available >= 0)'
\echo ');'
\prompt c

CREATE TABLE IF NOT EXISTS available_tool (
    tool_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_type TEXT NOT NULL,
    available INTEGER DEFAULT 5 NOT NULL,
    CHECK(available >= 0)
);

\echo
\echo 'CREATE TABLE IF NOT EXISTS checked_out_tool ('
\echo '    checked_out_by TEXT NOT NULL,'
\echo '    tool_id INTEGER NOT NULL REFERENCES available_tool'
\echo ');'
\prompt c

CREATE TABLE IF NOT EXISTS checked_out_tool (
    checked_out_by TEXT NOT NULL,
    tool_id INTEGER NOT NULL REFERENCES available_tool
);

\echo
\echo 'CREATE ASSERTION out_of_tools CHECK('
\echo '    NOT EXISTS ('
\echo '        SELECT 1'
\echo '        FROM'
\echo '            available_tool a'
\echo '        JOIN'
\echo '            checked_out_tool d'
\echo '            ON ('
\echo '                a.tool_id = d.tool_id'
\echo '            )'
\echo '        GROUP BY a.tool_id'
\echo '        HAVING count(*) > a.available'
\echo '    )'
\echo ');'
\prompt c

CREATE ASSERTION out_of_tools CHECK(
    NOT EXISTS (
        SELECT 1
        FROM
            available_tool a
        JOIN
            checked_out_tool d
            ON (
                a.tool_id = d.tool_id
            )
        GROUP BY a.tool_id
        HAVING count(*) > a.available
    )
);

\echo
\echo 'INSERT INTO available_tool (tool_type, available)'
\echo 'VALUES (''ball peen hammer'', 3);'
\prompt c

INSERT INTO available_tool (tool_type, available)
VALUES ('ball peen hammer', 3);

\echo
\echo 'INSERT INTO checked_out_tool(checked_out_by, tool_id)'
\echo 'VALUES'
\echo '    (''Leo'', 1),'
\echo '    (''Edith'', 1),'
\echo '    (''Ruth'', 1);'
\prompt c

INSERT INTO checked_out_tool(checked_out_by, tool_id)
VALUES
    ('Leo', 1),
    ('Edith', 1),
    ('Ruth', 1);

\echo
\echo 'This should fail:'
\echo
\echo 'INSERT INTO checked_out_tool(checked_out_by, tool_id)'
\echo '    (''Benny'', 1);'
\prompt c

INSERT INTO checked_out_tool(checked_out_by, tool_id)
VALUES
    ('Benny', 1);

\echo
\echo 'This should fail, too:'
\echo
\echo UPDATE available_tool
\echo SET available = 2
\echo WHERE tool_id = 1;
\prompt c

UPDATE available_tool
SET available = 2
WHERE tool_id = 1;

\echo 'Sad trombone'
\prompt c

DROP ASSERTION out_of_tools;
DROP TABLE checked_out_tool;
DROP TABLE available_tool;
